spring:
  application:
    name: kaimono-order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
