apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaimono-order-service
  labels:
    app: kaimono-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaimono-order-service
  template:
    metadata:
      labels:
        app: kaimono-order-service
    spec:
      containers:
        - name: kaimono-order-service
          image: kaimono-order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: KAIMONO_CATALOG_SERVICE_URI
              value: http://kaimono-catalog-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://kaimono-postgres/kaimonodb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://kaimono-postgres/kaimonodb_order
