apiVersion: v1
kind: Service
metadata:
  name: kaimono-order-service
  labels:
    app: kaimono-order-service
spec:
  type: ClusterIP
  selector:
    app: kaimono-order-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9002
